[SERVICE]
    Flush        5
    Daemon       Off
    Log_Level    info
    # Parsers_File parsers.conf # Uncomment if custom parsers are needed

[INPUT]
    Name         winlog
    Channels     Security,System,Application
    Interval_Sec 1
    DB           winlog.sqlite

[OUTPUT]
    Name        kafka
    Match       *
    Brokers     {{BROKER_URL}}
    Topics      windows-logs
    Timestamp_Key @timestamp
    Retry_Limit 5
    rdkafka.security.protocol SASL_SSL
    rdkafka.sasl.mechanism    PLAIN
    rdkafka.sasl.username     {{KAFKA_USER}}
    rdkafka.sasl.password     {{KAFKA_PASS}}
